package com.csc205.project2.shapes;

/**
 * Concrete implementation of a three-dimensional torus shape.
 *
 * <p>A torus is the surface of revolution generated by revolving a circle of
 * radius {@code innerRadius} (the tube radius) about an axis at a distance of
 * {@code outerRadius} (the distance from the center of the tube to the center
 * of the torus). This class extends {@link Shape3D} and provides the geometric
 * formulas for volume and surface area:</p>
 *
 * <ul>
 *   <li><b>Volume:</b> {@code V = 2π² × R × r²}</li>
 *   <li><b>Surface Area:</b> {@code SA = 4π² × R × r}</li>
 * </ul>
 *
 * <p>Where {@code R} is the {@code outerRadius} (major radius) and {@code r}
 * is the {@code innerRadius} (minor / tube radius).</p>
 *
 * <p>A geometric constraint is enforced: the {@code outerRadius} must be
 * strictly greater than the {@code innerRadius} to produce a valid,
 * non-self-intersecting torus.</p>
 *
 * <p>Example usage:</p>
 * <pre>{@code
 * Torus t = new Torus("MyTorus", "Purple", 2.0, 5.0);
 * System.out.println(t.getVolume());      // 394.7842
 * System.out.println(t.getSurfaceArea()); // 394.7842
 * System.out.println(t);                 // formatted toString output
 * }</pre>
 *
 * @author  YourName
 * @version 1.0
 * @see     Shape3D
 */
public class Torus extends Shape3D {

    // -------------------------------------------------------------------------
    // Fields
    // -------------------------------------------------------------------------

    /**
     * The inner (tube / minor) radius of the torus — the radius of the
     * circular cross-section of the tube, in units.
     * Must be strictly greater than zero and strictly less than
     * {@code outerRadius}.
     */
    private double innerRadius;

    /**
     * The outer (major) radius of the torus — the distance from the center
     * of the torus to the center of the tube, in units.
     * Must be strictly greater than {@code innerRadius}.
     */
    private double outerRadius;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Constructs a {@code Torus} with the specified name, color, inner radius,
     * and outer radius.
     *
     * @param name        the name of the torus; must not be {@code null} or blank
     * @param color       the color of the torus; must not be {@code null} or blank
     * @param innerRadius the tube (minor) radius; must be &gt; 0 and &lt;
     *                    {@code outerRadius}
     * @param outerRadius the major radius; must be strictly greater than
     *                    {@code innerRadius}
     * @throws IllegalArgumentException if either radius is not strictly positive,
     *                                  if {@code outerRadius} &le; {@code innerRadius},
     *                                  or if {@code name} / {@code color} is invalid
     */
    public Torus(String name, String color, double innerRadius, double outerRadius) {
        super(name, color);
        validateRadii(innerRadius, outerRadius);
        this.innerRadius = innerRadius;
        this.outerRadius = outerRadius;
    }

    /**
     * Constructs a default {@code Torus} with inner radius 1.0 and outer
     * radius 2.0 using the given name and color.
     *
     * @param name  the name of the torus; must not be {@code null} or blank
     * @param color the color of the torus; must not be {@code null} or blank
     */
    public Torus(String name, String color) {
        this(name, color, 1.0, 2.0);
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /**
     * Validates that the given inner and outer radii form a geometrically
     * valid torus.
     *
     * @param innerRadius the proposed tube radius
     * @param outerRadius the proposed major radius
     * @throws IllegalArgumentException if either value is &le; 0 or if
     *                                  {@code outerRadius} &le; {@code innerRadius}
     */
    private static void validateRadii(double innerRadius, double outerRadius) {
        if (innerRadius <= 0) {
            throw new IllegalArgumentException(
                    "Torus innerRadius must be greater than zero, but was: " + innerRadius);
        }
        if (outerRadius <= 0) {
            throw new IllegalArgumentException(
                    "Torus outerRadius must be greater than zero, but was: " + outerRadius);
        }
        if (outerRadius <= innerRadius) {
            throw new IllegalArgumentException(String.format(
                    "Torus outerRadius (%.4f) must be strictly greater than " +
                            "innerRadius (%.4f) to form a valid torus.", outerRadius, innerRadius));
        }
    }

    // -------------------------------------------------------------------------
    // Shape3D abstract method implementations
    // -------------------------------------------------------------------------

    /**
     * Calculates the volume of this torus using the formula:
     * <pre>V = 2π² × R × r²</pre>
     *
     * <p>Where {@code R} is the {@code outerRadius} and {@code r} is the
     * {@code innerRadius}.</p>
     *
     * @return the volume of the torus, always &gt; 0
     */
    @Override
    protected double calculateVolume() {
        return 2 * Math.PI * Math.PI * outerRadius * innerRadius * innerRadius;
    }

    /**
     * Calculates the total surface area of this torus using the formula:
     * <pre>SA = 4π² × R × r</pre>
     *
     * <p>Where {@code R} is the {@code outerRadius} and {@code r} is the
     * {@code innerRadius}.</p>
     *
     * @return the total surface area of the torus, always &gt; 0
     */
    @Override
    protected double calculateSurfaceArea() {
        return 4 * Math.PI * Math.PI * outerRadius * innerRadius;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the inner (tube / minor) radius of this torus.
     *
     * @return the inner radius in units; always &gt; 0 and &lt; {@code outerRadius}
     */
    public double getInnerRadius() {
        return innerRadius;
    }

    /**
     * Sets the inner (tube / minor) radius of this torus.
     *
     * <p>The new value must be strictly positive and strictly less than the
     * current {@code outerRadius}.</p>
     *
     * @param innerRadius the new inner radius; must be &gt; 0 and &lt;
     *                    current {@code outerRadius}
     * @throws IllegalArgumentException if the constraint is violated
     */
    public void setInnerRadius(double innerRadius) {
        validateRadii(innerRadius, this.outerRadius);
        this.innerRadius = innerRadius;
    }

    /**
     * Returns the outer (major) radius of this torus.
     *
     * @return the outer radius in units; always &gt; {@code innerRadius}
     */
    public double getOuterRadius() {
        return outerRadius;
    }

    /**
     * Sets the outer (major) radius of this torus.
     *
     * <p>The new value must be strictly greater than the current
     * {@code innerRadius}.</p>
     *
     * @param outerRadius the new outer radius; must be strictly greater than
     *                    current {@code innerRadius}
     * @throws IllegalArgumentException if the constraint is violated
     */
    public void setOuterRadius(double outerRadius) {
        validateRadii(this.innerRadius, outerRadius);
        this.outerRadius = outerRadius;
    }

    // -------------------------------------------------------------------------
    // Object overrides
    // -------------------------------------------------------------------------

    /**
     * Returns a formatted string representation of this torus, extending
     * the base {@link Shape3D#toString()} output with torus-specific
     * dimensional properties.
     *
     * <p>Example output:</p>
     * <pre>
     * Torus {
     *   Name         : MyTorus
     *   Color        : Purple
     *   Volume       : 394.7842 units³
     *   Surface Area : 394.7842 units²
     *   Inner Radius : 2.0000 units
     *   Outer Radius : 5.0000 units
     * }
     * </pre>
     *
     * @return a descriptive, multi-line string for this torus
     */
    @Override
    public String toString() {
        return String.format(
                "%s%n" +
                        "  Inner Radius : %.4f units%n" +
                        "  Outer Radius : %.4f units%n" +
                        "}",
                super.toString().substring(0, super.toString().lastIndexOf('}')).stripTrailing(),
                innerRadius,
                outerRadius
        );
    }

    /**
     * Indicates whether some other object is equal to this {@code Torus}.
     *
     * <p>Two tori are equal if their base class properties ({@code name} and
     * {@code color}) are equal and both {@code innerRadius} and
     * {@code outerRadius} match exactly.</p>
     *
     * @param obj the reference object with which to compare
     * @return {@code true} if the objects are equal; {@code false} otherwise
     */
    @Override
    public boolean equals(Object obj) {
        if (!super.equals(obj)) return false;
        Torus other = (Torus) obj;
        return Double.compare(innerRadius, other.innerRadius) == 0
                && Double.compare(outerRadius, other.outerRadius) == 0;
    }

    /**
     * Returns a hash code for this torus, consistent with
     * {@link #equals(Object)}.
     *
     * @return a hash code derived from the base class hash, {@code innerRadius},
     *         and {@code outerRadius}
     */
    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + Double.hashCode(innerRadius);
        result = 31 * result + Double.hashCode(outerRadius);
        return result;
    }
}